version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true

clash_rule_base = "https://raw.githubusercontent.com/Eternal460/ClashConfig/main/base.yml"

[[custom_groups]]
import = "https://raw.githubusercontent.com/Eternal460/ClashConfig/refs/heads/main/groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/Eternal460/ClashConfig/refs/heads/main/AllRulesets.toml"
