version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true

clash_rule_base = "https://raw.githubusercontent.com/Eternal460/Rule/main/base.yml"

[node_pref]
skip_cert_verify_flag = false

[[custom_groups]]
import = "https://raw.githubusercontent.com/Eternal460/Rule/main/groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/Eternal460/Rule/main/AllRulesets.toml"
