version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true
skip-cert-verify = false

clash_rule_base = "https://raw.githubusercontent.com/Eternal460/Rule/main/base.yml"

[[custom_groups]]
import = "https://raw.githubusercontent.com/Eternal460/Rule/refs/heads/main/groups.toml"

[[rulesets]]
import = "https://raw.githubusercontent.com/Eternal460/Rule/refs/heads/main/AllRulesets.toml"
